// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.9
// source: protobufs/entityblock.proto

package entityblock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EncryptedYjsDelta represents a single Yjs update encrypted with the entity's key.
// Used for collaborative content editing (papers, notes, tasks, etc.).
// The Yjs binary update is encrypted using XChaCha20-Poly1305 with the entity's key.
type EncryptedYjsDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // Yjs update encrypted with entity key
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`           // 24-byte XChaCha20 nonce (unique per delta)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedYjsDelta) Reset() {
	*x = EncryptedYjsDelta{}
	mi := &file_protobufs_entityblock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedYjsDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedYjsDelta) ProtoMessage() {}

func (x *EncryptedYjsDelta) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_entityblock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedYjsDelta.ProtoReflect.Descriptor instead.
func (*EncryptedYjsDelta) Descriptor() ([]byte, []int) {
	return file_protobufs_entityblock_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedYjsDelta) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedYjsDelta) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// Blocks groups multiple encrypted deltas for storage in EntityBlock.
// When a client makes edits, deltas are aggregated (debounced 750ms) into a Blocks message
// before being sent to the server. Other clients receive this block via SSE.
type Blocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deltas        []*EncryptedYjsDelta   `protobuf:"bytes,1,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blocks) Reset() {
	*x = Blocks{}
	mi := &file_protobufs_entityblock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blocks) ProtoMessage() {}

func (x *Blocks) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_entityblock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blocks.ProtoReflect.Descriptor instead.
func (*Blocks) Descriptor() ([]byte, []int) {
	return file_protobufs_entityblock_proto_rawDescGZIP(), []int{1}
}

func (x *Blocks) GetDeltas() []*EncryptedYjsDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

var File_protobufs_entityblock_proto protoreflect.FileDescriptor

const file_protobufs_entityblock_proto_rawDesc = "" +
	"\n" +
	"\x1bprotobufs/entityblock.proto\x12\ventityblock\"I\n" +
	"\x11EncryptedYjsDelta\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\"@\n" +
	"\x06Blocks\x126\n" +
	"\x06deltas\x18\x01 \x03(\v2\x1e.entityblock.EncryptedYjsDeltaR\x06deltasB\x1aZ\x18shape/models/entityblockb\x06proto3"

var (
	file_protobufs_entityblock_proto_rawDescOnce sync.Once
	file_protobufs_entityblock_proto_rawDescData []byte
)

func file_protobufs_entityblock_proto_rawDescGZIP() []byte {
	file_protobufs_entityblock_proto_rawDescOnce.Do(func() {
		file_protobufs_entityblock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufs_entityblock_proto_rawDesc), len(file_protobufs_entityblock_proto_rawDesc)))
	})
	return file_protobufs_entityblock_proto_rawDescData
}

var file_protobufs_entityblock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufs_entityblock_proto_goTypes = []any{
	(*EncryptedYjsDelta)(nil), // 0: entityblock.EncryptedYjsDelta
	(*Blocks)(nil),            // 1: entityblock.Blocks
}
var file_protobufs_entityblock_proto_depIdxs = []int32{
	0, // 0: entityblock.Blocks.deltas:type_name -> entityblock.EncryptedYjsDelta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobufs_entityblock_proto_init() }
func file_protobufs_entityblock_proto_init() {
	if File_protobufs_entityblock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufs_entityblock_proto_rawDesc), len(file_protobufs_entityblock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobufs_entityblock_proto_goTypes,
		DependencyIndexes: file_protobufs_entityblock_proto_depIdxs,
		MessageInfos:      file_protobufs_entityblock_proto_msgTypes,
	}.Build()
	File_protobufs_entityblock_proto = out.File
	file_protobufs_entityblock_proto_goTypes = nil
	file_protobufs_entityblock_proto_depIdxs = nil
}
